name: Dev-qa Test Checker

on:
#triggers the workflow on push and pull request events for master
  push:
    branches:
    - qa
    
#do running work flow from button
  workflow_dispatch:

jobs:
  test-checker:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'SKIP SCRIPTS')"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: harishdhandeorg/Automationrun
          ref: main
          token: ${{secrets.MYTOKENACCESS}}

      - name: Install QAENv
        run: |
           npm init -y
           npm install 
    
      - name: Conditional Statements to Check Smoke to Run
        if: "contains(github.event.head_commit.message, 'smoke')"
        run: |
            echo "this is smoke test execution"
            make test-run-smoke
  
      - name: Conditional Statements to Check Regression to Run
        if: "contains(github.event.head_commit.message, 'regression')"
        run: |
            echo "this is Regression test execution"
            make test-run-regression
      
      - name: Conditional Statements to Check Sanity to Run
        if: "contains(github.event.head_commit.message, 'sanity')"
        run: |
            echo "this is Sanity test execution"
            make test-run-sanity
            
      # publish artifacts
      - name: Publish Artifacts for Determined Setup
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: reportHtml
